sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: ccodd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  wechat:
    appid: ${WECHAT_APPID:}
    secret: ${WECHAT_SECRET:}
    mchid: ${WECHAT_MCHID:}
    mch-serial-no: ${WECHAT_MCH_SERIAL_NO:}
    private-key-file-path: ${WECHAT_PRIVATE_KEY_FILE_PATH:}
    api-v3-key: ${WECHAT_API_V3_KEY:}
    we-chat-pay-cert-file-path: ${WECHAT_PAY_CERT_FILE_PATH:}
    notify-url: ${WECHAT_NOTIFY_URL:}
    refund-notify-url: ${WECHAT_REFUND_NOTIFY_URL:}
